### ISSUE TITLE
How to use Node2vec to train the data?

### ISSUE THREAD

**Issue by thatgirls** [kckishan/HOGCN-LP#3]
There seems to be something wrong with your code. When I embedded the nodes using Node2vec, the code did not run successfully

**Comment by kckishan** [comment]
Hi @thatgirls, thanks for letting me know about this issue. I have fixed the issue and updated the code here. I hope you can run the code successfully now. If you find any issues, let me know.

**Comment by thatgirls** [comment]
Thank you very much. The code is running successfully.

**Comment by kckishan** [comment]
You are welcome. 

I believe the issue is now resolved. So, I close the issue.
